name: Lints

on: [push]

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.1.1
        with:
          version: nightly

      - name: Install Dependencies
        run: yarn install
      - name: Install Forge Dependencies
        run: forge install
